version: "3"
services:
  app:    
    build: .
    volumes:
      - ./:/app    
    ports:
      - "3000:8080"
    depends_on:
       - "rediscache"
       - "mongodb"      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  rediscache:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: "exit 0"      
